### ISSUE TITLE
Docker image won't run.

### ISSUE THREAD

**Issue by richpav** [BBC-News-Labs/audiogram#18]
FWIW, I'm not expert in Docker, but I built the image on MacOS. Here's what happened when I tried to run it.

```
$ docker run -p 8888:8888 -t -i audiogram
Starting local redis
nohup: appending output to 'nohup.out'
curl: (7) Failed to connect to audiogram.newslabs.co port 8081: Connection refused
/home/audiogram/src/lib/transports/redis/remote.js:14
    throw err;
    ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/local/nvm/versions/node/v6.12.0/bin/node" "/usr/local/nvm/versions/node/v6.12.0/bin/npm" "run" "debug"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! audiogram@3.6.1 debug: `DEBUG=1 bin/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the audiogram@3.6.1 debug script 'DEBUG=1 bin/server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the audiogram package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     DEBUG=1 bin/server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs audiogram
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls audiogram
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/audiogram/src/npm-debug.log
```

**Comment by noirimipsum** [comment]
i get this same error on mint/ubuntu
